import { QuizData } from "./App";

export const quizData: QuizData[] = [
  { latex: "\\int", correctAnswers: ["int"], level: "easy" },
  { latex: "\\sum", correctAnswers: ["sum"], level: "easy" },
  { latex: "\\alpha", correctAnswers: ["alpha"], level: "easy" },
  { latex: "\\infty", correctAnswers: ["infty"], level: "easy" },
  { latex: "\\sqrt{x}", correctAnswers: ["sqrt{x}"], level: "medium" },
  { latex: "\\frac{a}{b}", correctAnswers: ["frac{a}{b}"], level: "medium" },
  { latex: "\\leq", correctAnswers: ["le", "leq"], level: "medium" },
  { latex: "\\geq", correctAnswers: ["ge", "geq"], level: "medium" },
  { latex: "\\rightarrow", correctAnswers: ["rightarrow", "to"], level: "medium" },
  { latex: "\\leftarrow", correctAnswers: ["leftarrow", "gets"], level: "medium" },
  { latex: "\\cdot", correctAnswers: ["cdot"], level: "easy" },
  { latex: "\\times", correctAnswers: ["times"], level: "easy" },
  {
    latex: "{\\color{lightgray} a} \\times {\\color{lightgray} b}",
    correctAnswers: ["times"],
    level: "easy",
  },
  { latex: "\\beta", correctAnswers: ["beta"], level: "easy" },
  { latex: "\\Gamma", correctAnswers: ["Gamma"], level: "medium" },
  { latex: "\\partial", correctAnswers: ["partial"], level: "medium" },
  { latex: "\\neq", correctAnswers: ["neq"], level: "medium" },
  { latex: "\\approx", correctAnswers: ["approx"], level: "medium" },
  { latex: "\\pi", correctAnswers: ["pi"], level: "easy" },
  { latex: "\\log", correctAnswers: ["log"], level: "medium" },
  { latex: "\\sin", correctAnswers: ["sin"], level: "medium" },
  { latex: "\\cos", correctAnswers: ["cos"], level: "medium" },
  { latex: "\\nabla", correctAnswers: ["nabla"], level: "hard" },
  { latex: "\\propto", correctAnswers: ["propto"], level: "hard" },
  { latex: "\\in", correctAnswers: ["in"], level: "hard" },
  { latex: "\\notin", correctAnswers: ["notin"], level: "hard" },
  { latex: "\\subseteq", correctAnswers: ["subseteq"], level: "hard" },
  { latex: "\\supseteq", correctAnswers: ["supseteq"], level: "hard" },
  { latex: "\\cup", correctAnswers: ["cup"], level: "hard" },
  { latex: "\\cap", correctAnswers: ["cap"], level: "hard" },
  { latex: "\\equiv", correctAnswers: ["equiv"], level: "hard" },
  { latex: "\\perp", correctAnswers: ["perp"], level: "hard" },
  { latex: "\\parallel", correctAnswers: ["parallel"], level: "hard" },
  { latex: "\\forall", correctAnswers: ["forall"], level: "hard" },
  { latex: "\\exists", correctAnswers: ["exists"], level: "hard" },
  { latex: "\\therefore", correctAnswers: ["therefore"], level: "hard" },
  { latex: "\\because", correctAnswers: ["because"], level: "hard" },
];
