import { QuizData } from "./App";

export const quizData: QuizData[] = [
  {
    latex: "\\sum_{\\color{lightgray} i=1}^{\\color{lightgray} n}",
    correctAnswers: ["sum"],
    level: "easy",
  },
  { latex: "\\sqrt{{\\color{lightgray} x}}", correctAnswers: ["sqrt{x}"], level: "easy" },
  { latex: "\\int", correctAnswers: ["int"], level: "easy" },
  { latex: "\\infty", correctAnswers: ["infty"], level: "easy" },
  { latex: "\\alpha", correctAnswers: ["alpha"], level: "easy" },
  { latex: "\\Delta", correctAnswers: ["Delta"], level: "easy" },
  { latex: "\\pi", correctAnswers: ["pi"], level: "easy" },
  { latex: "\\leq", correctAnswers: ["le", "leq"], level: "easy" },
  { latex: "\\geq", correctAnswers: ["ge", "geq"], level: "easy" },
  { latex: "\\neq", correctAnswers: ["ne", "neq"], level: "easy" },
  {
    latex: "{\\color{lightgray} a} \\times {\\color{lightgray} b}",
    correctAnswers: ["times"],
    level: "easy",
  },
  {
    latex: "{\\color{lightgray} a} \\div {\\color{lightgray} b}",
    correctAnswers: ["div"],
    level: "easy",
  },
  {
    latex: "{\\color{lightgray} a} \\cdot {\\color{lightgray} b}",
    correctAnswers: ["cdot"],
    level: "easy",
  },
  { latex: "\\in", correctAnswers: ["in"], level: "easy" },
  { latex: "\\subset", correctAnswers: ["subset"], level: "easy" },
  { latex: "\\supset", correctAnswers: ["supset"], level: "easy" },
  { latex: "\\cup", correctAnswers: ["cup"], level: "easy" },
  { latex: "\\cap", correctAnswers: ["cap"], level: "easy" },
  { latex: "\\Rightarrow", correctAnswers: ["Rightarrow"], level: "easy" },
  { latex: "\\Leftarrow", correctAnswers: ["Leftarrow"], level: "easy" },
  { latex: "\\Rightleftarrow", correctAnswers: ["RightLeftarrow"], level: "easy" },
  { latex: "\\angle", correctAnswers: ["angle"], level: "easy" },
  { latex: "\\flat", correctAnswers: ["flat"], level: "easy" },
  { latex: "\\natural", correctAnswers: ["natural"], level: "easy" },
  { latex: "\\sharp", correctAnswers: ["sharp"], level: "easy" },

  { latex: "\\forall", correctAnswers: ["forall"], level: "medium" },
  { latex: "\\exists", correctAnswers: ["exists"], level: "medium" },
  { latex: "\\neg", correctAnswers: ["neg", "lnot"], level: "medium" },
  { latex: "\\land", correctAnswers: ["land", "wedge"], level: "medium" },
  { latex: "\\lor", correctAnswers: ["lor", "vee"], level: "medium" },
  {
    latex: "{\\color{lightgray} a} \\pm {\\color{lightgray} b}",
    correctAnswers: ["pm"],
    level: "medium",
  },
  {
    latex: "{\\color{lightgray} a} \\bigodot {\\color{lightgray} b}",
    correctAnswers: ["bigodot"],
    level: "medium",
  },
  {
    latex: "\\prod_{\\color{lightgray} i=1}^{\\color{lightgray} n}",
    correctAnswers: ["prod"],
    level: "medium",
  },
  { latex: "\\vec{{\\color{lightgray} a}}", correctAnswers: ["vec{a}"], level: "medium" },
  { latex: "\\approx", correctAnswers: ["approx"], level: "medium" },
  { latex: "\\sim", correctAnswers: ["sim"], level: "medium" },
  { latex: "\\mapsto", correctAnswers: ["mapsto"], level: "medium" },
  { latex: "\\leqq", correctAnswers: ["leqq"], level: "medium" },
  { latex: "\\geqq", correctAnswers: ["geqq"], level: "medium" },
  { latex: "\\coloneqq", correctAnswers: ["coloneqq", "coloneq"], level: "medium" },
  { latex: "\\Gamma", correctAnswers: ["Gamma"], level: "medium" },
  { latex: "\\Theta", correctAnswers: ["Theta"], level: "medium" },
  { latex: "\\Xi", correctAnswers: ["Xi"], level: "medium" },
  { latex: "\\xi", correctAnswers: ["xi"], level: "medium" },
  { latex: "\\rho", correctAnswers: ["rho"], level: "medium" },
  { latex: "\\nu", correctAnswers: ["nu"], level: "medium" },
  { latex: "\\varepsilon", correctAnswers: ["varepsilon"], level: "medium" },
  { latex: "\\varphi", correctAnswers: ["varphi"], level: "medium" },
  { latex: "\\Psi", correctAnswers: ["Psi"], level: "medium" },
  { latex: "\\partial", correctAnswers: ["partial"], level: "medium" },
  { latex: "\\nabla", correctAnswers: ["nabla"], level: "medium" },
  { latex: "\\emptyset", correctAnswers: ["emptyset"], level: "medium" },
  { latex: "\\rightarrow", correctAnswers: ["rightarrow", "to"], level: "medium" },
  { latex: "\\leftarrow", correctAnswers: ["leftarrow", "gets"], level: "medium" },
  { latex: "\\therefore", correctAnswers: ["therefore"], level: "medium" },
  { latex: "\\because", correctAnswers: ["because"], level: "medium" },
  { latex: "\\equiv", correctAnswers: ["equiv"], level: "medium" },
  { latex: "\\dag", correctAnswers: ["dag", "dagger"], level: "medium" },
  { latex: "\\P", correctAnswers: ["P"], level: "medium" },
  { latex: "\\S", correctAnswers: ["S"], level: "medium" },

  { latex: "\\prec", correctAnswers: ["prec"], level: "hard" },
  { latex: "\\succ", correctAnswers: ["succ"], level: "hard" },
  { latex: "\\lll", correctAnswers: ["lll"], level: "hard" },
  { latex: "\\ggg", correctAnswers: ["ggg"], level: "hard" },
  { latex: "\\Bumpeq", correctAnswers: ["Bumpeq"], level: "hard" },
  { latex: "\\Upsilon", correctAnswers: ["Upsilon"], level: "hard" },
  { latex: "\\varkappa", correctAnswers: ["varkappa"], level: "hard" },
  { latex: "\\varpi", correctAnswers: ["varpi"], level: "hard" },
  { latex: "\\aleph", correctAnswers: ["aleph"], level: "hard" },
  { latex: "\\beth", correctAnswers: ["beth"], level: "hard" },
  { latex: "\\gimel", correctAnswers: ["gimel"], level: "hard" },
  { latex: "\\daleth", correctAnswers: ["daleth"], level: "hard" },
  { latex: "\\eth", correctAnswers: ["eth"], level: "hard" },
  { latex: "\\wp", correctAnswers: ["wp"], level: "hard" },
  { latex: "\\Re", correctAnswers: ["Re"], level: "hard" },
  { latex: "\\Im", correctAnswers: ["Im"], level: "hard" },
  { latex: "\\Bbbk", correctAnswers: ["Bbbk"], level: "hard" },
  { latex: "\\mho", correctAnswers: ["mho"], level: "hard" },
  { latex: "\\maltese", correctAnswers: ["maltese"], level: "hard" },
  { latex: "\\ell", correctAnswers: ["ell"], level: "hard" },
  { latex: "\\AA", correctAnswers: ["AA"], level: "hard" },
  { latex: "\\ss", correctAnswers: ["ss"], level: "hard" },
  { latex: "\\looparrowright", correctAnswers: ["looparrowright"], level: "hard" },
  { latex: "\\looparrowleft", correctAnswers: ["looparrowleft"], level: "hard" },
];
